title: Resume - Vsevolod Mineev
description:  Personal Profile, Education and Skills of Sebastian Mineev.
url: https://www.sebastian-mineev.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier
    - jekyll-seo-tag

exclude:
  - docker-compose.yml
